server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/inmobiliaria
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update #create-drop | update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      indent_output: true

# Swagger UI disponible en: http://localhost:8080/swagger-ui.html
springdoc:
  api-docs:
    path: /api-docs

# Configuraci√≥n del seed
app:
  seed:
    enabled: false   # true para ejecutar el seed, false para no ejecutarlo
    reset: false    # true para borrar datos antes de insertar

frontend:
  url: http://localhost:3000